[2024-04-30T10:46:23.330+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-30T10:46:23.763+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dog.get_dog_api scheduled__2024-04-30T03:57:00+00:00 [queued]>
[2024-04-30T10:46:23.927+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dog.get_dog_api scheduled__2024-04-30T03:57:00+00:00 [queued]>
[2024-04-30T10:46:23.928+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-30T10:46:24.102+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): get_dog_api> on 2024-04-30 03:57:00+00:00
[2024-04-30T10:46:24.186+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=35510) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-30T10:46:24.195+0000] {standard_task_runner.py:63} INFO - Started process 35602 to run task
[2024-04-30T10:46:24.181+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dog', 'get_dog_api', 'scheduled__2024-04-30T03:57:00+00:00', '--job-id', '326', '--raw', '--subdir', 'DAGS_FOLDER/dog.py', '--cfg-path', '/tmp/tmpbb0ls3zu']
[2024-04-30T10:46:24.217+0000] {standard_task_runner.py:91} INFO - Job 326: Subtask get_dog_api
[2024-04-30T10:46:24.455+0000] {task_command.py:426} INFO - Running <TaskInstance: dog.get_dog_api scheduled__2024-04-30T03:57:00+00:00 [running]> on host 9822fb6f757c
[2024-04-30T10:46:25.164+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dog' AIRFLOW_CTX_TASK_ID='get_dog_api' AIRFLOW_CTX_EXECUTION_DATE='2024-04-30T03:57:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-30T03:57:00+00:00'
[2024-04-30T10:46:25.177+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-30T10:46:26.127+0000] {dog.py:15} INFO - {'message': 'https://images.dog.ceo/breeds/shiba/shiba-16.jpg', 'status': 'success'}
[2024-04-30T10:46:26.132+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-30T10:46:26.133+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dog.py", line 17, in _get_dog_api
    data = json.load(f)
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 98 (char 97)
[2024-04-30T10:46:26.148+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=dog, task_id=get_dog_api, execution_date=20240430T035700, start_date=20240430T104623, end_date=20240430T104626
[2024-04-30T10:46:26.229+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 326 for task get_dog_api (Extra data: line 1 column 98 (char 97); 35602)
[2024-04-30T10:46:26.343+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-30T10:46:26.416+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-30T10:46:26.454+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
