[2024-04-30T10:47:43.515+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-30T10:47:43.979+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dog.get_dog_api scheduled__2024-04-30T04:47:00+00:00 [queued]>
[2024-04-30T10:47:44.033+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dog.get_dog_api scheduled__2024-04-30T04:47:00+00:00 [queued]>
[2024-04-30T10:47:44.037+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-30T10:47:44.532+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): get_dog_api> on 2024-04-30 04:47:00+00:00
[2024-04-30T10:47:44.612+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=36378) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-30T10:47:44.621+0000] {standard_task_runner.py:63} INFO - Started process 36490 to run task
[2024-04-30T10:47:44.691+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dog', 'get_dog_api', 'scheduled__2024-04-30T04:47:00+00:00', '--job-id', '372', '--raw', '--subdir', 'DAGS_FOLDER/dog.py', '--cfg-path', '/tmp/tmpjceyzuvm']
[2024-04-30T10:47:44.715+0000] {standard_task_runner.py:91} INFO - Job 372: Subtask get_dog_api
[2024-04-30T10:47:45.127+0000] {task_command.py:426} INFO - Running <TaskInstance: dog.get_dog_api scheduled__2024-04-30T04:47:00+00:00 [running]> on host 9822fb6f757c
[2024-04-30T10:47:45.654+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dog' AIRFLOW_CTX_TASK_ID='get_dog_api' AIRFLOW_CTX_EXECUTION_DATE='2024-04-30T04:47:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-30T04:47:00+00:00'
[2024-04-30T10:47:45.658+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-30T10:47:46.656+0000] {dog.py:15} INFO - {'message': 'https://images.dog.ceo/breeds/terrier-wheaten/n02098105_3700.jpg', 'status': 'success'}
[2024-04-30T10:47:46.656+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-30T10:47:46.659+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dog.py", line 17, in _get_dog_api
    data = json.load(f)
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 98 (char 97)
[2024-04-30T10:47:46.716+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=dog, task_id=get_dog_api, execution_date=20240430T044700, start_date=20240430T104743, end_date=20240430T104746
[2024-04-30T10:47:46.847+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 372 for task get_dog_api (Extra data: line 1 column 98 (char 97); 36490)
[2024-04-30T10:47:46.965+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-30T10:47:47.167+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-30T10:47:47.254+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
