[2024-04-30T10:45:18.695+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-30T10:45:18.792+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dog.get_dog_api scheduled__2024-04-30T03:38:00+00:00 [queued]>
[2024-04-30T10:45:18.838+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dog.get_dog_api scheduled__2024-04-30T03:38:00+00:00 [queued]>
[2024-04-30T10:45:18.847+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-30T10:45:18.879+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): get_dog_api> on 2024-04-30 03:38:00+00:00
[2024-04-30T10:45:18.928+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dog', 'get_dog_api', 'scheduled__2024-04-30T03:38:00+00:00', '--job-id', '310', '--raw', '--subdir', 'DAGS_FOLDER/dog.py', '--cfg-path', '/tmp/tmptxbhc0ln']
[2024-04-30T10:45:18.931+0000] {standard_task_runner.py:91} INFO - Job 310: Subtask get_dog_api
[2024-04-30T10:45:18.935+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=34881) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-30T10:45:18.939+0000] {standard_task_runner.py:63} INFO - Started process 34947 to run task
[2024-04-30T10:45:19.050+0000] {task_command.py:426} INFO - Running <TaskInstance: dog.get_dog_api scheduled__2024-04-30T03:38:00+00:00 [running]> on host 9822fb6f757c
[2024-04-30T10:45:19.223+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dog' AIRFLOW_CTX_TASK_ID='get_dog_api' AIRFLOW_CTX_EXECUTION_DATE='2024-04-30T03:38:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-30T03:38:00+00:00'
[2024-04-30T10:45:19.225+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-30T10:45:19.622+0000] {dog.py:15} INFO - {'message': 'https://images.dog.ceo/breeds/terrier-welsh/lucy.jpg', 'status': 'success'}
[2024-04-30T10:45:19.623+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-30T10:45:19.624+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dog.py", line 17, in _get_dog_api
    data = json.load(f)
                     ^^^
NameError: name 'jsonfile' is not defined
[2024-04-30T10:45:19.652+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=dog, task_id=get_dog_api, execution_date=20240430T033800, start_date=20240430T104518, end_date=20240430T104519
[2024-04-30T10:45:19.673+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 310 for task get_dog_api (name 'jsonfile' is not defined; 34947)
[2024-04-30T10:45:19.746+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-30T10:45:19.765+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-30T10:45:19.777+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
