[2024-04-30T10:35:27.577+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-30T10:35:27.638+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dog.get_dog_api scheduled__2024-03-23T00:12:00+00:00 [queued]>
[2024-04-30T10:35:27.653+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dog.get_dog_api scheduled__2024-03-23T00:12:00+00:00 [queued]>
[2024-04-30T10:35:27.653+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-30T10:35:27.673+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): get_dog_api> on 2024-03-23 00:12:00+00:00
[2024-04-30T10:35:27.716+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dog', 'get_dog_api', 'scheduled__2024-03-23T00:12:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/dog.py', '--cfg-path', '/tmp/tmpjt48kibx']
[2024-04-30T10:35:27.737+0000] {standard_task_runner.py:91} INFO - Job 20: Subtask get_dog_api
[2024-04-30T10:35:27.739+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=29083) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-30T10:35:27.740+0000] {standard_task_runner.py:63} INFO - Started process 29144 to run task
[2024-04-30T10:35:27.908+0000] {task_command.py:426} INFO - Running <TaskInstance: dog.get_dog_api scheduled__2024-03-23T00:12:00+00:00 [running]> on host 9822fb6f757c
[2024-04-30T10:35:28.391+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dog' AIRFLOW_CTX_TASK_ID='get_dog_api' AIRFLOW_CTX_EXECUTION_DATE='2024-03-23T00:12:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-23T00:12:00+00:00'
[2024-04-30T10:35:28.399+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-30T10:35:29.546+0000] {dog.py:15} INFO - {'message': 'https://images.dog.ceo/breeds/schnauzer-miniature/n02097047_5205.jpg', 'status': 'success'}
[2024-04-30T10:35:29.549+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-30T10:35:29.549+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dog.py", line 17, in _get_dog_api
    json.dump(f, data)
  File "/usr/local/lib/python3.12/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/local/lib/python3.12/json/encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type TextIOWrapper is not JSON serializable
[2024-04-30T10:35:29.613+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=dog, task_id=get_dog_api, execution_date=20240323T001200, start_date=20240430T103527, end_date=20240430T103529
[2024-04-30T10:35:30.006+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 20 for task get_dog_api (Object of type TextIOWrapper is not JSON serializable; 29144)
[2024-04-30T10:35:30.117+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-30T10:35:30.218+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-30T10:35:30.239+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
