[2024-04-30T10:48:59.879+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-30T10:49:00.212+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dog.get_dog_api scheduled__2024-04-30T05:34:00+00:00 [queued]>
[2024-04-30T10:49:00.331+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dog.get_dog_api scheduled__2024-04-30T05:34:00+00:00 [queued]>
[2024-04-30T10:49:00.335+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-30T10:49:02.192+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): get_dog_api> on 2024-04-30 05:34:00+00:00
[2024-04-30T10:49:02.291+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=37190) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-30T10:49:02.292+0000] {standard_task_runner.py:63} INFO - Started process 37322 to run task
[2024-04-30T10:49:02.298+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dog', 'get_dog_api', 'scheduled__2024-04-30T05:34:00+00:00', '--job-id', '420', '--raw', '--subdir', 'DAGS_FOLDER/dog.py', '--cfg-path', '/tmp/tmpgkchofmb']
[2024-04-30T10:49:02.322+0000] {standard_task_runner.py:91} INFO - Job 420: Subtask get_dog_api
[2024-04-30T10:49:02.642+0000] {task_command.py:426} INFO - Running <TaskInstance: dog.get_dog_api scheduled__2024-04-30T05:34:00+00:00 [running]> on host 9822fb6f757c
[2024-04-30T10:49:03.330+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dog' AIRFLOW_CTX_TASK_ID='get_dog_api' AIRFLOW_CTX_EXECUTION_DATE='2024-04-30T05:34:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-30T05:34:00+00:00'
[2024-04-30T10:49:03.337+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-30T10:49:04.088+0000] {dog.py:15} INFO - {'message': 'https://images.dog.ceo/breeds/corgi-cardigan/n02113186_10416.jpg', 'status': 'success'}
[2024-04-30T10:49:04.089+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-30T10:49:04.090+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dog.py", line 17, in _get_dog_api
    data = json.load(f)
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 98 (char 97)
[2024-04-30T10:49:04.137+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=dog, task_id=get_dog_api, execution_date=20240430T053400, start_date=20240430T104900, end_date=20240430T104904
[2024-04-30T10:49:04.301+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 420 for task get_dog_api (Extra data: line 1 column 98 (char 97); 37322)
[2024-04-30T10:49:04.477+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-30T10:49:04.617+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-30T10:49:04.654+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
